# Stage 1 - Builder

FROM python:3.12 AS builder

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .


# Stage 2 - Runtime

FROM python:3.12-slim

WORKDIR /app

COPY --from=builder /app /app

RUN pip install --no-cache-dir flask

EXPOSE 5000

CMD ["python", "app.py"]
